/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostRouteImport } from './routes/post'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CharteRouteImport } from './routes/charte'
import { Route as BoxesRouteImport } from './routes/boxes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AffiliationRouteImport } from './routes/affiliation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as DealsSlugRouteImport } from './routes/deals.$slug'
import { Route as CCatRouteImport } from './routes/c.$cat'

const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CharteRoute = CharteRouteImport.update({
  id: '/charte',
  path: '/charte',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesRoute = BoxesRouteImport.update({
  id: '/boxes',
  path: '/boxes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliationRoute = AffiliationRouteImport.update({
  id: '/affiliation',
  path: '/affiliation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsSlugRoute = DealsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DealsRoute,
} as any)
const CCatRoute = CCatRouteImport.update({
  id: '/c/$cat',
  path: '/c/$cat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliation': typeof AffiliationRoute
  '/auth': typeof AuthRoute
  '/boxes': typeof BoxesRoute
  '/charte': typeof CharteRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/post': typeof PostRoute
  '/c/$cat': typeof CCatRoute
  '/deals/$slug': typeof DealsSlugRoute
  '/u/$handle': typeof UHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliation': typeof AffiliationRoute
  '/auth': typeof AuthRoute
  '/boxes': typeof BoxesRoute
  '/charte': typeof CharteRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/post': typeof PostRoute
  '/c/$cat': typeof CCatRoute
  '/deals/$slug': typeof DealsSlugRoute
  '/u/$handle': typeof UHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliation': typeof AffiliationRoute
  '/auth': typeof AuthRoute
  '/boxes': typeof BoxesRoute
  '/charte': typeof CharteRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/post': typeof PostRoute
  '/c/$cat': typeof CCatRoute
  '/deals/$slug': typeof DealsSlugRoute
  '/u/$handle': typeof UHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliation'
    | '/auth'
    | '/boxes'
    | '/charte'
    | '/contact'
    | '/deals'
    | '/leaderboard'
    | '/post'
    | '/c/$cat'
    | '/deals/$slug'
    | '/u/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliation'
    | '/auth'
    | '/boxes'
    | '/charte'
    | '/contact'
    | '/deals'
    | '/leaderboard'
    | '/post'
    | '/c/$cat'
    | '/deals/$slug'
    | '/u/$handle'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/affiliation'
    | '/auth'
    | '/boxes'
    | '/charte'
    | '/contact'
    | '/deals'
    | '/leaderboard'
    | '/post'
    | '/c/$cat'
    | '/deals/$slug'
    | '/u/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AffiliationRoute: typeof AffiliationRoute
  AuthRoute: typeof AuthRoute
  BoxesRoute: typeof BoxesRoute
  CharteRoute: typeof CharteRoute
  ContactRoute: typeof ContactRoute
  DealsRoute: typeof DealsRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  PostRoute: typeof PostRoute
  CCatRoute: typeof CCatRoute
  UHandleRoute: typeof UHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charte': {
      id: '/charte'
      path: '/charte'
      fullPath: '/charte'
      preLoaderRoute: typeof CharteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes': {
      id: '/boxes'
      path: '/boxes'
      fullPath: '/boxes'
      preLoaderRoute: typeof BoxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliation': {
      id: '/affiliation'
      path: '/affiliation'
      fullPath: '/affiliation'
      preLoaderRoute: typeof AffiliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$slug': {
      id: '/deals/$slug'
      path: '/$slug'
      fullPath: '/deals/$slug'
      preLoaderRoute: typeof DealsSlugRouteImport
      parentRoute: typeof DealsRoute
    }
    '/c/$cat': {
      id: '/c/$cat'
      path: '/c/$cat'
      fullPath: '/c/$cat'
      preLoaderRoute: typeof CCatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DealsRouteChildren {
  DealsSlugRoute: typeof DealsSlugRoute
}

const DealsRouteChildren: DealsRouteChildren = {
  DealsSlugRoute: DealsSlugRoute,
}

const DealsRouteWithChildren = DealsRoute._addFileChildren(DealsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AffiliationRoute: AffiliationRoute,
  AuthRoute: AuthRoute,
  BoxesRoute: BoxesRoute,
  CharteRoute: CharteRoute,
  ContactRoute: ContactRoute,
  DealsRoute: DealsRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  PostRoute: PostRoute,
  CCatRoute: CCatRoute,
  UHandleRoute: UHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
